services:
  app:
    image: petstore
    build: 
      context: .
    container_name: petstore1.0
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_user}
      - POSTGRES_PASSWORD=${DB_password}
      - POSTGRES_DB=${DB_name}
    ports:
      - "5433:${DB_port}"
    restart: always
    