// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/pet/": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Обновить информацию, id и фото изменить нельзя. Категории: 1 - dog, 2 - cat. Tags: 1 - friendly, 2 - wild, 3 - trained",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "pet"
                ],
                "summary": "Обновить информацию о питомце",
                "parameters": [
                    {
                        "description": "Заполни все поля для изменения",
                        "name": "pet",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_modules_pet_controller.Pet"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное обновление информации или не ошибочное сообщение",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Неверной формат",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Аутентификация не пройдена",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Авторизация не пройдена",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Создание и добавление нового питомца с различными полями. Отсчёт будет идти от id (не должен повторяться). В категориях и тегах указывается только id. Категории: 1 - dog, 2 - cat. Tags: 1 - friendly, 2 - wild, 3 - trained. Также доступно 3 статуса: available, sold и pending",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "pet"
                ],
                "summary": "Добавить нового питомца в магазин",
                "parameters": [
                    {
                        "description": "Заполни все поля для добавления",
                        "name": "pet",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_modules_pet_controller.Pet"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное добавление или не ошибочное сообщение",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Неверной формат",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Аутентификация не пройдена",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Авторизация не пройдена",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/pet/findByStatus": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получить всех животных по статусу",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pet"
                ],
                "summary": "Получить всех животных по статусу",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Статус питомца (available, sold, pending)",
                        "name": "status",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное получение животных или не ошибочное сообщение",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_modules_pet_controller.OutputPetArray"
                            }
                        }
                    },
                    "400": {
                        "description": "Неверной формат",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Аутентификация не пройдена",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Авторизация не пройдена",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/pet/photo/{petId}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Добавить фото конкретному питомцу, будет сохранено локально, адрес можете узнать в поле photoUrl",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "pet"
                ],
                "summary": "Добавить фото питомца",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Введи id питомца",
                        "name": "petId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Добавь изображение животного",
                        "name": "photoFile",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное добавление фото или не ошибочное сообщение",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Неверной формат",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Аутентификация не пройдена",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Авторизация не пройдена",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/pet/{petId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получить одного животного по id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pet"
                ],
                "summary": "Получить животного по id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id питомца",
                        "name": "petId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Получить одного животного или не ошибочное сообщение",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_pet_controller.OutputPet"
                        }
                    },
                    "400": {
                        "description": "Неверной формат структуры",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Аутентификация не пройдена",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Авторизация не пройдена",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Обновить только name и status.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "pet"
                ],
                "summary": "Обновить информацию о питомце",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Введи Id животного",
                        "name": "petId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Имя питомца",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Статус питомца (available, sold, pending)",
                        "name": "status",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное обновление информации или не ошибочное сообщение",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Неверной формат",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Аутентификация не пройдена",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Авторизация не пройдена",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Удалить одного животного по id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "pet"
                ],
                "summary": "Удалить животного по id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id питомца",
                        "name": "petId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное удаление или не ошибочное сообщение",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Неверной формат структуры",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Аутентификация не пройдена",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Авторизация не пройдена",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/store/order": {
            "post": {
                "description": "Создание заказа на животное. Отсчёт по id (не должен повторяться). Нулевые значения у полей integer не допускаются",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "order"
                ],
                "summary": "Разместить заказ на животное",
                "parameters": [
                    {
                        "description": "Заполни все поля для размещения заказа",
                        "name": "order",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_modules_order_controller.Order"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное размещение заказа или не ошибочное сообщение",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Неверной формат",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/store/order/{orderId}": {
            "get": {
                "description": "Получить заказ по Id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "order"
                ],
                "summary": "Получить заказ по Id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Введите id заказа",
                        "name": "orderId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Структура заказа или не ошибочное сообщение",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_order_controller.Order"
                        }
                    },
                    "400": {
                        "description": "Неверной формат структуры",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удалить заказ по Id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "order"
                ],
                "summary": "Удалить заказ по Id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Введите id заказа",
                        "name": "orderId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное удаление заказа или не ошибочное сообщение",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Неверной формат структуры",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/": {
            "post": {
                "description": "Создание нового пользователя или восстановление удалённого с различными полями. Отсчёт будет идти от username (не должен повторяться)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Регистрация нового пользователя",
                "parameters": [
                    {
                        "description": "Заполни все поля для регистрации",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_modules_user_controller.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешная регистрация или не ошибочное сообщение",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Неверной формат структуры",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/createWithArray": {
            "post": {
                "description": "Создание новой группы пользователей с различными полями. Отсчёт будет идти от username (не должен повторяться). Для восстановления аккаунта воспользуйтесь одиночной регистрацией",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Регистрация группы пользователей",
                "parameters": [
                    {
                        "description": "Заполни все поля для регистрации",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_modules_user_controller.UserArray"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешная регистрация или не ошибочное сообщение",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Неверной формат структуры",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "get": {
                "description": "Создание токена jwt и отправка в заголовке для дальнейшей авторизации",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Вход в систему",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Укажи username",
                        "name": "username",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Укажи пароль",
                        "name": "password",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный вход в систему или не ошибочное сообщение",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Неверной формат",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/logout": {
            "get": {
                "description": "Аннулирование jwt токена с использованием black_list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Выход из системы",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Укажи username",
                        "name": "username",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Укажи пароль",
                        "name": "password",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Bearer токен доступа для имитации отправки браузером. Обязательно укажите Bearer перед вставкой токена",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный выход из системы или не ошибочное сообщение",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Неверной формат",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/{username}": {
            "get": {
                "description": "Получить полную информацию о пользователе",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Получить информацию о пользователе",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Укажи username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное получение информации или не ошибочное сообщение",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_user_controller.User"
                        }
                    },
                    "400": {
                        "description": "Неверной формат",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "Нельзя обновить на то имя пользователя, которое уже есть в базе",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Обновить информацию о пользователе",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Укажи username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Заполни все поля для обновления информации",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_modules_user_controller.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное обновление информации или не ошибочное сообщение",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Неверной формат",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Мягкое удаление пользователя (проставление даты)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Удаление пользователя",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Укажи username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное удаление или не ошибочное сообщение",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Неверной формат",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_modules_order_controller.Order": {
            "type": "object",
            "required": [
                "complete",
                "id",
                "petId",
                "quantity",
                "shipDate",
                "status"
            ],
            "properties": {
                "complete": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer",
                    "minimum": 1
                },
                "petId": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                },
                "shipDate": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "internal_modules_pet_controller.Category": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "integer",
                    "maximum": 2,
                    "minimum": 1
                }
            }
        },
        "internal_modules_pet_controller.OutputPet": {
            "type": "object",
            "properties": {
                "category_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "photoUrl": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_modules_pet_controller.OutputTag"
                    }
                }
            }
        },
        "internal_modules_pet_controller.OutputPetArray": {
            "type": "object",
            "properties": {
                "pets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_modules_pet_controller.OutputPet"
                    }
                }
            }
        },
        "internal_modules_pet_controller.OutputTag": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "internal_modules_pet_controller.Pet": {
            "type": "object",
            "required": [
                "category",
                "id",
                "name",
                "status",
                "tags"
            ],
            "properties": {
                "category": {
                    "$ref": "#/definitions/internal_modules_pet_controller.Category"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_modules_pet_controller.Tag"
                    }
                }
            }
        },
        "internal_modules_pet_controller.Tag": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "integer",
                    "maximum": 3,
                    "minimum": 1
                }
            }
        },
        "internal_modules_user_controller.User": {
            "type": "object",
            "required": [
                "email",
                "firstName",
                "lastName",
                "password",
                "phone",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "internal_modules_user_controller.UserArray": {
            "type": "object",
            "properties": {
                "user": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_modules_user_controller.User"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Petstore",
	Description:      "Зоомагазин, который работает с тремя основными сущностями: пользователь, животное и магазин.\nЗдесь доступны CRUD-операции над всеми сущностями, мягкая работа с пользователем (проставление дат действий), авторизация и выход из системы с помощью чёрного списка, загрузка изображения и сохранение локально на сервере. Это самые интересные возможности, попробуйте сами",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
